"""CausalOpsBench: operational root-cause analysis over sensor telemetry.

Source: https://github.com/pz1004/causalopsbench-public

An episode contains a component ``topology``, ``observations`` (a sensor time
series), operator ``manuals``, and ``ground_truth.fault`` -- the faulty
component, its fault type and the propagation path.  The benchmark's own task is
sequential (choose mitigations under cost/safety constraints); the abductive
core is identifying the fault that explains the telemetry, which is what this
adapter evaluates.

**Episode source.** ``data/dev.jsonl`` holds only 8 public episodes, so the
adapter prefers the released episode files under ``results/*/episodes/*.jsonl``
(500 episodes per seed, same schema, generated by the benchmark's own
generator).  Which file was used is reported; ``options.episode_file`` pins it.
Model *predictions* under ``results/*/predictions/`` are never read.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from ..core.adapter import SkippedDataset
from ..core.metrics import aggregate_mean_metrics, contains_match, extract_answer_span
from ..core.types import AdapterDocumentation, ModelResponse, SampleScore, SampleSpec
from . import _common as C
from ._base import PooledDatasetAdapter, unparsed_score

REPO_URL = "https://github.com/pz1004/causalopsbench-public"


class CausalOpsBenchAdapter(PooledDatasetAdapter):
    """Identify the faulty component and fault type from telemetry."""

    adapter_version = "1.0"

    system_prompt = (
        "You are an expert at abductive reasoning: inferring the explanation that, if true, "
        "would best account for the evidence you are given. You are given operational "
        "telemetry from a running system. Identify the faulty component and the kind of fault "
        "that together explain the observed symptoms."
    )
    data_delivery_mode = "static"
    objective_metrics = True
    selection_cardinality = "single"
    primary_metric = "component_match"

    def load_items(self) -> list[dict[str, Any]]:
        root = C.ensure_git_repo(
            REPO_URL, self.context.data_dir / "repo", offline=self.context.offline
        )
        pinned = self.context.option("episode_file")
        candidates: list[Any] = []
        if pinned:
            candidates = [root / str(pinned)]
        else:
            candidates = C.find_files(root / "results", ["episodes/*.jsonl"])
            candidates += C.find_files(root / "data", ["dev.jsonl"])
        for path in candidates:
            if not path.exists():
                continue
            rows = [row for row in C.read_jsonl(path) if (row.get("ground_truth") or {}).get("fault")]
            if not rows:
                continue
            self._episode_file = str(path.relative_to(root))
            self.split_used = (
                f"{self._episode_file} ({len(rows)} episodes with ground-truth faults); the public "
                "release keeps its test seeds unpublished, so a released episode set is used"
            )
            return rows
        raise SkippedDataset("no CausalOpsBench episode file with ground-truth faults was found")

    def make_sample(self, item: dict[str, Any], index: int) -> SampleSpec | None:
        fault = (item.get("ground_truth") or {}).get("fault") or {}
        component = C.normalize_whitespace(fault.get("component"))
        fault_type = C.normalize_whitespace(fault.get("fault_type"))
        observations = item.get("observations") or []
        topology = item.get("topology") or []
        if not component or not observations:
            return None

        stride = max(1, len(observations) // int(self.context.option("max_timepoints", 12)))
        rows = []
        for record in observations[::stride][: int(self.context.option("max_timepoints", 12))]:
            sensors = record.get("sensors") or {}
            values = ", ".join(f"{key}={value}" for key, value in sorted(sensors.items()))
            rows.append(f"t={record.get('timestamp')}: {values}")
        topology_text = ", ".join(
            f"{edge[0]} -> {edge[1]}" for edge in topology if isinstance(edge, (list, tuple)) and len(edge) >= 2
        )
        manuals = [
            C.normalize_whitespace(entry.get("text"))
            for entry in (item.get("manuals") or [])
            if C.normalize_whitespace(entry.get("text"))
        ]
        components = sorted({str(node) for edge in topology for node in edge})
        return SampleSpec(
            sample_id=C.stable_id("causalops", item.get("episode_id", index)),
            fields={
                "context": (
                    f"System topology: {topology_text}\n"
                    + (f"Components: {', '.join(components)}\n" if components else "")
                    + ("Operator notes:\n" + "\n".join(f"- {note}" for note in manuals) if manuals else "")
                ),
                "observation": "Sensor readings over time:\n" + "\n".join(rows),
                "question": (
                    "Which component is faulty, and what kind of fault explains these readings?"
                ),
                "instructions": (
                    "Name the faulty component exactly as it appears in the topology, and the "
                    "fault type as a short hyphenated label (for example "
                    "'oxygen-transfer-loss')."
                ),
            },
            reference={
                "component": component,
                "fault_type": fault_type,
                "path": C.as_list(fault.get("root_cause_path")),
            },
            task_kind="generation",
            # Reading a sensor table then naming a component and a fault type.
            max_tokens=1024,
            metadata={
                "episode_id": item.get("episode_id"),
                "domain": item.get("domain"),
                "severity": fault.get("severity"),
                "n_observations": len(observations),
            },
        )

    def score(
        self,
        sample: SampleSpec,
        response: ModelResponse,
        *,
        output_contract: dict[str, Any] | None = None,
    ) -> SampleScore:
        text = response.text
        if not text.strip():
            return unparsed_score(["component_match", "fault_type_match"], raw=text[:200])
        reference = sample.reference
        component_variants = _variants(reference["component"])
        fault_variants = _variants(reference["fault_type"])
        metrics = {
            "component_match": float(
                any(contains_match(text, variant) for variant in component_variants)
            ),
            "fault_type_match": float(
                any(contains_match(text, variant) for variant in fault_variants)
            ),
        }
        metrics["full_diagnosis"] = float(
            metrics["component_match"] and metrics["fault_type_match"]
        )
        domain = sample.metadata.get("domain")
        if domain:
            metrics[f"component_match_{domain}"] = metrics["component_match"]
        return SampleScore(
            metrics=metrics,
            prediction=(extract_answer_span(text, output_contract) or text)[:300],
            details={"gold": f"{reference['component']} / {reference['fault_type']}"},
        )

    def aggregate(self, scores: Sequence[SampleScore]) -> dict[str, float]:
        return aggregate_mean_metrics([score.metrics for score in scores])

    def documentation(self) -> AdapterDocumentation:
        return AdapterDocumentation(
            dataset_id=self.dataset_id,
            name="CausalOpsBench",
            domain="Computing Systems: Operational RCA",
            source_url=REPO_URL,
            processing_mode="Generation",
            split_used=self.split_used,
            abductive_subset=(
                "Fault identification from telemetry. The benchmark's mitigation-planning loop "
                "(choosing actions under cost and safety constraints) is decision-making rather "
                "than abduction and is not evaluated."
            ),
            sampling_procedure=self.sampling_note(),
            metrics_description={
                "component_match": "1 if the response names the faulty component (primary)",
                "fault_type_match": "1 if the response names the gold fault type",
                "full_diagnosis": "1 only if both are named",
                "component_match_<domain>": "the primary metric per simulated domain",
            },
            primary_metric="component_match",
            decisions=[
                "Preferred a released 500-episode file over data/dev.jsonl (8 episodes), because "
                "the public repository keeps its test seeds unpublished; which file was used is "
                "recorded in split_used and can be pinned with options.episode_file.",
                "Never read results/*/predictions/, which are other models' outputs.",
                "Sub-sampled the 60-point sensor series to 12 evenly spaced timepoints so the "
                "prompt stays inside the input budget while preserving the trend.",
                "Included the operator manuals shipped with the episode, since a human diagnostician "
                "would have them.",
            ],
            caveats=[
                "Episodes are synthetic (generator 'causalopsbench.synthetic.v1'), so scores "
                "measure telemetry-pattern reasoning rather than real-incident diagnosis.",
                "Sub-sampling the time series can hide a short transient that identifies the fault.",
            ],
            statistics={
                **self.base_statistics(),
                "episode_file": getattr(self, "_episode_file", ""),
                "max_timepoints": int(self.context.option("max_timepoints", 12)),
            },
        )


def _variants(label: str) -> list[str]:
    if not label:
        return []
    base = label.strip()
    return list({base, base.replace("-", " "), base.replace("_", " "), base.replace("-", "_")})
